/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/gapura.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Gapura(props) {
  const { nodes, materials } = useGLTF("./models/gapura.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      {/* <group
        position={[37.27, 1.99, 10.63]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cube4230.geometry}
          material={materials["Stone.050"]}
        />
        <mesh
          geometry={nodes.Cube4230_1.geometry}
          material={materials["StoneDark.011"]}
        />
      </group> */}
      <group
        position={[2.11, 8.32, -0.02]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.61}
      >
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[2.24, 10.05, -0.17]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[8.83, 0.58, 0.3]}
      />
      <group
        position={[2.19, 12.4, -0.07]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[7.62, 0.58, 1.62]}
      >
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[2.15, 11.97, -0.07]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.58, 0.42, 0.58]}
      >
        <mesh
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.Material}
        />
      </group>
      <group
        position={[2.15, 13.39, -0.07]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.58, 0.47, 0.58]}
      >
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[1.37, 10.06, -0.12]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.58}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[3.32, 9.94, -0.03]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={-0.58}
      />
    </group>
  );
}

useGLTF.preload("./models/gapura.glb");
