/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/gedung3.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Gedung3(props) {
  const { nodes, materials } = useGLTF("./models/gedung3.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group scale={1.89}>
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane_4.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Plane_5.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Plane_6.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group
        position={[3.84, 0, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.89, 3.22, 1.89]}
      >
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane001_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane001_4.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Plane001_5.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Plane001_6.geometry}
          material={materials["Material.008"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/gedung3.glb");
