/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/gedung7.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Gedung7(props) {
  const { nodes, materials } = useGLTF("./models/gedung7.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group scale={[5.55, 2.75, 2.75]}>
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        scale={[5.55, 2.75, 2.75]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[-4.53, 3.76, -1.76]}
      />
      <group
        position={[-3.72, 3.96, 2.87]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.47, 0.47, 0.8]}
      >
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Plane002_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[-5.67, 3.96, -1.9]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.47, 0.47, 0.8]}
      >
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Plane004_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[-3.05, 1.32, -2.89]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.47, 0.47, 0.8]}
      >
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane005_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Plane005_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[-9.71, 2.29, 4.48]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 1, 1.82]}
      >
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Plane006_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Plane006_3.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.009"]}
        position={[-4.53, 3.76, -1.76]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["Material.010"]}
        position={[0, 0, 0.05]}
        scale={7.71}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.001"]}
        position={[4.47, 3.37, -1.61]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.65, -0.63, -0.9]}
      />
      <group
        position={[2.18, 3.58, 2.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.35, 0.51, 0.61]}
      >
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane003_2.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Plane003_3.geometry}
          material={materials["Material.005"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/gedung7.glb");
