/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/palm-tree.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PalmTree(props) {
  const { nodes, materials } = useGLTF("./models/palm-tree.gltf");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <mesh
        geometry={nodes.Group_152.geometry}
        material={materials["wood.011"]}
        position={[0.01, 1.36, -0.04]}
        scale={1.38}
      />
      <mesh
        geometry={nodes.Group_154.geometry}
        material={materials["leaves.001"]}
        position={[0.01, 3.53, 0.01]}
        scale={1.8}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("./models/palm-tree.gltf");
