/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/rockWall.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RockWall(props) {
  const { nodes, materials } = useGLTF("./models/rockWall.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group
        position={[-10.86, 1.99, 8.33]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Cube4230.geometry}
          material={materials["Stone.050"]}
        />
        <mesh
          geometry={nodes.Cube4230_1.geometry}
          material={materials["StoneDark.011"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/rockWall.glb");
