/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/short-palm-tree.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ShortPalmTree(props) {
  const { nodes, materials } = useGLTF("./models/short-palm-tree.gltf");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <mesh
        geometry={nodes.Group_28.geometry}
        material={materials["wood.013"]}
        position={[0.02, 1.13, -0.07]}
        scale={1.12}
      />
      <mesh
        geometry={nodes.Group_30.geometry}
        material={materials["leaves.003"]}
        position={[0.02, 2.83, -0.03]}
        scale={0.81}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("./models/short-palm-tree.gltf");
