/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/gnParang.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function GnParang(props) {
  const { nodes, materials } = useGLTF("./models/gnParang.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group position={[3.55, 3.71, 2.71]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[3.06, 3.49, 2.71]} rotation={[0, 1.57, 0]} scale={0.03}>
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[3.57, 3.41, 3.06]} rotation={[0, 1.57, 0]} scale={0.03}>
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube003_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[0.68, 3.71, 1.03]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.43, 3.71, 1.76]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube005_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.32, 3.71, 0.97]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube006_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube006_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.54, 3.56, 1.64]}
        rotation={[0, 1.57, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube007_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.32, 2.26, 3.24]}
        rotation={[0, 1.57, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube009_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube009_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.86, 3.61, 1.59]}
        rotation={[0, -1.5, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube012_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[6.28, 3.02, 2.35]} rotation={[0, -1.5, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[5.45, 2.9, 2.87]} rotation={[0, -1.5, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube014_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.24, 2.25, 3.15]} rotation={[0, -1.5, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube015_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube015_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-5.9, 0.62, 6.87]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube016_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube016_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.03, 0.32, 6.23]}
        rotation={[0, 1.57, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube017_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.66, 0.32, 6.23]}
        rotation={[0, 0.53, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube018_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube018_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.08, 0.32, 7.47]} rotation={[0, 0.79, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube019_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube019_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[3.36, 0.62, 8.29]} rotation={[0, 0.79, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube020_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube020_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.69, 0.06, -0.05]}
        rotation={[0, Math.PI / 2, 0]}
        scale={13.1}
      >
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        position={[5.02, 0.85, 7.89]}
        rotation={[Math.PI, -0.71, 0]}
        scale={[-0.49, -0.27, -0.27]}
      >
        <mesh
          geometry={nodes.Cube027.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube027_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[-0.35, 0.85, 9.59]}
        rotation={[Math.PI, -0.71, 0]}
        scale={[-0.49, -0.27, -0.27]}
      >
        <mesh
          geometry={nodes.Cube029.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube029_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[-4.68, 0.84, 6.31]}
        rotation={[Math.PI, -0.71, 0]}
        scale={[-0.49, -0.27, -0.27]}
      >
        <mesh
          geometry={nodes.Cube030.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube030_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[-0.91, 1.75, 2.97]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.NurbsPath.geometry}
        material={nodes.NurbsPath.material}
        position={[0, -0.09, 0.11]}
      />
      <group
        position={[2.74, 0.98, 10.01]}
        rotation={[0, -0.38, 0]}
        scale={[1.41, 0.76, 0.06]}
      >
        <mesh
          geometry={nodes.Cube024.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Cube024_1.geometry}
          material={materials["foto 1"]}
        />
      </group>
      <group
        position={[4.93, 0.87, 10.55]}
        rotation={[0, -0.43, 0]}
        scale={[0.74, 0.76, 0.06]}
      >
        <mesh
          geometry={nodes.Cube025.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Cube025_1.geometry}
          material={materials["foto 2"]}
        />
      </group>
      <group
        position={[6.45, 0.87, 10.85]}
        rotation={[0, -0.4, 0]}
        scale={[0.74, 0.76, 0.06]}
      >
        <mesh
          geometry={nodes.Cube026.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Cube026_1.geometry}
          material={materials["foto 3"]}
        />
      </group>
      <group
        position={[7.97, 1, 11.19]}
        rotation={[0, -0.4, 0]}
        scale={[0.74, 0.76, 0.06]}
      >
        <mesh
          geometry={nodes.Cube028.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Cube028_1.geometry}
          material={materials["foto 4"]}
        />
      </group>
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Material.015"]}
        position={[2.73, 0.7, 10.08]}
        rotation={[Math.PI / 2, 0, 0.38]}
        scale={0.22}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.015"]}
        position={[4.42, 0.75, 10.39]}
        rotation={[Math.PI / 2, 0, 0.43]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={materials["Material.015"]}
        position={[4.3, 0.64, 10.34]}
        rotation={[Math.PI / 2, 0, 0.43]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Text004.geometry}
        material={materials["Material.015"]}
        position={[6.15, 0.76, 10.79]}
        rotation={[Math.PI / 2, 0, 0.4]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Text005.geometry}
        material={materials["Material.015"]}
        position={[5.81, 0.67, 10.65]}
        rotation={[Math.PI / 2, 0, 0.4]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Text006.geometry}
        material={materials["Material.015"]}
        position={[7.79, 0.86, 11.18]}
        rotation={[Math.PI / 2, 0, 0.4]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Text007.geometry}
        material={materials["Material.015"]}
        position={[7.32, 0.77, 10.98]}
        rotation={[Math.PI / 2, 0, 0.4]}
        scale={0.05}
      />
    </group>
  );
}

useGLTF.preload("./models/gnParang.glb");
