/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/gnParang.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function GnParang(props) {
  const { nodes, materials } = useGLTF("./models/gnParang.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group position={[3.55, 3.71, 2.71]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[3.06, 3.49, 2.71]} rotation={[0, 1.57, 0]} scale={0.03}>
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[3.57, 3.41, 3.06]} rotation={[0, 1.57, 0]} scale={0.03}>
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube003_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[0.68, 3.71, 1.03]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.43, 3.71, 1.76]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube005_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.32, 3.71, 0.97]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube006_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube006_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.54, 3.56, 1.64]}
        rotation={[0, 1.57, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube007_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.32, 2.26, 3.24]}
        rotation={[0, 1.57, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube009_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube009_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.27, 1.28, 4.07]}
        rotation={[0, -1.5, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube012_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[6.28, 3.02, 2.35]} rotation={[0, -1.5, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[5.45, 2.9, 2.87]} rotation={[0, -1.5, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube014_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.24, 2.25, 3.15]} rotation={[0, -1.5, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube015_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube015_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[-5.9, 0.62, 6.87]} rotation={[0, 1.57, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube016_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube016_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.03, 0.32, 6.23]}
        rotation={[0, 1.57, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube017_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.66, 0.32, 6.23]}
        rotation={[0, 0.53, 0]}
        scale={0.05}
      >
        <mesh
          geometry={nodes.Cube018_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube018_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[1.08, 0.32, 7.47]} rotation={[0, 0.79, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube019_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[3.36, 0.62, 8.29]} rotation={[0, 0.79, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Cube020.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube020_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-0.69, 0.06, -0.05]}
        rotation={[0, Math.PI / 2, 0]}
        scale={13.1}
      >
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        position={[5.02, 0.85, 7.89]}
        rotation={[Math.PI, -0.71, 0]}
        scale={[-0.49, -0.27, -0.27]}
      >
        <mesh
          geometry={nodes.Cube027.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube027_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[-0.35, 0.85, 9.59]}
        rotation={[Math.PI, -0.71, 0]}
        scale={[-0.49, -0.27, -0.27]}
      >
        <mesh
          geometry={nodes.Cube029.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube029_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[-4.68, 0.84, 6.31]}
        rotation={[Math.PI, -0.71, 0]}
        scale={[-0.49, -0.27, -0.27]}
      >
        <mesh
          geometry={nodes.Cube030.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube030_1.geometry}
          material={materials["Material.007"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/gnParang.glb");
