/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/pendopo.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pendopo(props) {
  const { nodes, materials } = useGLTF("./models/pendopo.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group position={[7.74, 2.91, 9.32]} scale={0.81}>
        <mesh
          geometry={nodes.Group_30_1.geometry}
          material={materials["leaves.003"]}
        />
        <mesh
          geometry={nodes.Group_30_2.geometry}
          material={materials["wood.013"]}
        />
      </group>
      <group
        position={[7.15, 2.91, -11.42]}
        rotation={[0, 1.57, 0]}
        scale={0.81}
      >
        <mesh
          geometry={nodes.Group_30001_1.geometry}
          material={materials["leaves.003"]}
        />
        <mesh
          geometry={nodes.Group_30001_2.geometry}
          material={materials["wood.013"]}
        />
      </group>
      <group position={[0.11, 0.05, 10.07]} scale={[1.63, 0.38, 0.07]}>
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials.foto1} />
      </group>
      <group position={[-3.35, 0.1, 10.07]} scale={[0.76, 0.38, 0.07]}>
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials.foto3} />
      </group>
      <group position={[3.73, 0.07, 10.07]} scale={[0.76, 0.38, 0.07]}>
        <mesh
          geometry={nodes.Plane007_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane007_2.geometry} material={materials.foto2} />
      </group>
      <group position={[0.02, 0.64, 0]} scale={[5.4, 4.26, 6.33]}>
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["wood.013"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Plane_4.geometry}
          material={materials["Material.012"]}
        />
      </group>
      <group position={[4.84, 0.7, 5.85]} scale={0.29}>
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[5.06, 0.7, -3.88]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.29}
      >
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.001"]}
        position={[4.84, 0.7, 5.85]}
        scale={0.29}
      />
      <group position={[5.12, 0.86, 10.09]} scale={0.29}>
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane005_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.008"]}
        position={[-0.01, 3.6, 0.06]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-5.47, -0.26, -6.28]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.007"]}
        position={[-0.02, 3.44, 0.06]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-6.16, -0.29, -7.07]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Material.007"]}
        position={[0.1, 6.32, 0.01]}
        scale={1.13}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.003"]}
        position={[0.08, 0.7, 10.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Material.003"]}
        position={[3, 0.92, 10.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.003"]}
        position={[3, 0.8, 10.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={materials["Material.003"]}
        position={[-4.08, 0.95, 10.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Text004.geometry}
        material={materials["Material.003"]}
        position={[-4.07, 0.82, 10.15]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[3.73, 0.06, 10.05]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.98, -1, -0.24]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[0.11, 0.06, 10.05]}
        rotation={[0, 0, -Math.PI]}
        scale={[-1.81, -1, -0.24]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[-3.34, 0.1, 10.05]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.98, -1, -0.24]}
      />
    </group>
  );
}

useGLTF.preload("./models/pendopo.glb");
