/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/situBuleud.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function SituBuleud(props) {
  const { nodes, materials } = useGLTF("./models/situBuleud.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group
        position={[0.01, 1.75, 0.01]}
        rotation={[-0.01, 0, -Math.PI / 2]}
        scale={0.23}
      >
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[-2.55, 5.09, 0.03]}
        rotation={[0, 1.13, -Math.PI / 2]}
        scale={2.24}
      >
        <mesh
          geometry={nodes.Group_152_1.geometry}
          material={materials["wood.011"]}
        />
        <mesh
          geometry={nodes.Group_152_2.geometry}
          material={materials["leaves.001"]}
        />
        <mesh
          geometry={nodes.Group_152_3.geometry}
          material={materials["wood.013"]}
        />
        <mesh
          geometry={nodes.Group_152_4.geometry}
          material={materials["leaves.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.013"]}
        position={[0, 0.21, 0]}
      />
      <group position={[19.97, 0.3, 4.67]} rotation={[0, 1.29, 0]} scale={0.86}>
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane009_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        position={[20.09, 0.3, -4.31]}
        rotation={[0, -1.29, -Math.PI]}
        scale={-0.86}
      >
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane011_1.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.006"]}
        position={[0, 0.24, 0]}
        scale={10.62}
      />
      <group position={[0, -0.89, 0]} scale={11.36}>
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Circle001_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group position={[0, -1.27, 0.09]} scale={12.55}>
        <mesh
          geometry={nodes.Circle002_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Circle002_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["Material.010"]}
        position={[0, 0.42, 0]}
        scale={13.99}
      />
      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials["Material.006"]}
        position={[-0.04, -1.52, 0.1]}
        scale={[17.99, 12.55, 17.99]}
      />
      <group position={[-0.04, -1.52, 0.1]} scale={[17.99, 12.55, 17.99]}>
        <mesh
          geometry={nodes.Circle006.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Circle006_1.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Circle006_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.005"]}
        position={[-0.01, 1.25, 0]}
        scale={[0.03, 0.37, 0.03]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.011"]}
        position={[0.01, 0.32, -0.1]}
        scale={11.41}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[6.85, 0.38, 0.24]}
        scale={[4.24, 0.31, 1]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0.56, 1.25, 0.24]}
        scale={[2.33, 1, 2.33]}
      />
    </group>
  );
}

useGLTF.preload("./models/situBuleud.glb");
