/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/wadukJatiluhur.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WadukJatiluhur(props) {
  const { nodes, materials } = useGLTF("./models/wadukJatiluhur.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.08, 0]} scale={8.12}>
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane_4.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[0, 0.38, 7.58]} scale={[7.11, 1, 0.45]}>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.003"]}
        scale={13.79}
      />
      <group position={[0.12, 0.14, 4.87]} rotation={[0, 0.09, 0]}>
        <mesh
          geometry={nodes.Circle_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Circle_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[0.12, 0.54, 4.87]}
        rotation={[0, 0.09, 0]}
        scale={[1, 0.66, 1]}
      >
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Circle001_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.005"]}
        position={[0.11, 0.08, -0.01]}
        scale={[6.42, 1.02, 6.42]}
      />
    </group>
  );
}

useGLTF.preload("./models/wadukJatiluhur.glb");
