/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/wadukjatiluhur.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function WadukJatiluhur(props) {
  const { nodes, materials } = useGLTF("./models/wadukjatiluhur.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group
        position={[5.29, 0.74, 9.54]}
        rotation={[0, -0.37, 0]}
        scale={[0.44, 0.22, 0.04]}
      >
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials.foto3} />
      </group>
      <group
        position={[3.98, 0.12, 9.43]}
        rotation={[0, -0.38, 0]}
        scale={[0.44, 0.22, 0.04]}
      >
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials.foto2} />
      </group>
      <group
        position={[5.18, 0.12, 9.04]}
        rotation={[0, -0.35, 0]}
        scale={[0.44, 0.22, 0.04]}
      >
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials.foto4} />
      </group>
      <group
        position={[5.13, 0.12, 8.62]}
        rotation={[0, -0.35, 0]}
        scale={[0.44, 0.22, 0.04]}
      >
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials.foto5} />
      </group>
      <group
        position={[2.12, 0.12, 9.11]}
        rotation={[0, -0.45, 0]}
        scale={[0.88, 0.22, 0.04]}
      >
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials.foto1} />
      </group>
      <group position={[0, 0.08, 0]} scale={8.12}>
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane_4.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group position={[0, 0.38, 7.58]} scale={[7.11, 1, 0.45]}>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.003"]}
        scale={13.79}
      />
      <group position={[0.12, 0.14, 4.87]} rotation={[0, 0.09, 0]}>
        <mesh
          geometry={nodes.Circle_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Circle_2.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[0.12, 0.54, 4.87]}
        rotation={[0, 0.09, 0]}
        scale={[1, 0.66, 1]}
      >
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Circle001_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.005"]}
        position={[0.11, 0.08, -0.01]}
        scale={[6.42, 1.02, 6.42]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.007"]}
        position={[2.11, 0.49, 9.15]}
        rotation={[Math.PI / 2, 0, 0.45]}
        scale={0.24}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Material.007"]}
        position={[3.68, 0.61, 9.36]}
        rotation={[Math.PI / 2, 0, 0.38]}
        scale={0.48}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.007"]}
        position={[3.68, 0.54, 9.36]}
        rotation={[Math.PI / 2, 0, 0.38]}
        scale={0.48}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={materials["Material.007"]}
        position={[5.01, 0.61, 9.95]}
        rotation={[Math.PI / 2, 0, 0.37]}
        scale={0.48}
      />
      <mesh
        geometry={nodes.Text004.geometry}
        material={materials["Material.007"]}
        position={[5.29, 0.38, 9.57]}
        rotation={[Math.PI / 2, 0, 0.37]}
        scale={0.48}
      />
      <mesh
        geometry={nodes.Text005.geometry}
        material={materials["Material.007"]}
        position={[6.24, 0.61, 9.47]}
        rotation={[Math.PI / 2, 0, 0.35]}
        scale={0.37}
      />
      <mesh
        geometry={nodes.Text006.geometry}
        material={materials["Material.007"]}
        position={[6.26, 0.56, 9.48]}
        rotation={[Math.PI / 2, 0, 0.35]}
        scale={0.44}
      />
      <mesh
        geometry={nodes.Text007.geometry}
        material={materials["Material.007"]}
        position={[7.56, 0.65, 9.54]}
        rotation={[Math.PI / 2, 0, 0.35]}
        scale={0.29}
      />
      <mesh
        geometry={nodes.Text008.geometry}
        material={materials["Material.007"]}
        position={[7.59, 0.53, 9.55]}
        rotation={[Math.PI / 2, 0, 0.35]}
        scale={0.44}
      />
    </group>
  );
}

useGLTF.preload("/wadukjatiluhur.glb");
