/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/KontenSideMuseum.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function KontenSideMuseum(props) {
  const { nodes, materials } = useGLTF("./models/KontenSideMuseum.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-4.58, 1.04, -2.92]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.11, 1, 1]}
      />
      <group
        position={[8.55, 1.02, 1.42]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["foto depan 1"]}
        />
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group
        position={[8.55, 1.02, 0.02]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane005.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={materials["Foto depan 2"]}
        />
      </group>
      <group
        position={[8.55, 1.02, -3.29]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane006.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        position={[5.85, 1.02, 1.53]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane007.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane007_1.geometry}
          material={materials["foto sejarah 1"]}
        />
      </group>
      <group
        position={[5.85, 1.02, 0.06]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane008.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane008_1.geometry}
          material={materials["foto sejarah 2"]}
        />
      </group>
      <group
        position={[5.85, 1.02, -1.41]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane009.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane009_1.geometry}
          material={materials["foto sejarah 3"]}
        />
      </group>
      <group
        position={[2.78, 1.02, 1.55]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.51, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane011_1.geometry}
          material={materials["foto sejarah 5"]}
        />
      </group>
      <group
        position={[2.78, 1.02, -1.54]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane012_1.geometry}
          material={materials["foto sejarah 4"]}
        />
      </group>
      <group
        position={[2.59, 1.02, 4.31]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.51, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane014.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane014_1.geometry}
          material={materials["foto masjid agung"]}
        />
        <mesh
          geometry={nodes.Plane014_2.geometry}
          material={materials["foto gedung kembar"]}
        />
        <mesh
          geometry={nodes.Plane014_3.geometry}
          material={materials["foto situ wanayasa"]}
        />
        <mesh
          geometry={nodes.Plane014_4.geometry}
          material={materials["foto pendopo"]}
        />
      </group>
      <group
        position={[2.52, 1.07, -1.28]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane017.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane017_1.geometry}
          material={materials["foto bupati 1"]}
        />
        <mesh
          geometry={nodes.Plane017_2.geometry}
          material={materials["foto bupati 2"]}
        />
      </group>
      <group
        position={[-3.99, 1.07, -1.94]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.63, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane019.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane019_1.geometry}
          material={materials["foto bupati 3"]}
        />
        <mesh
          geometry={nodes.Plane019_2.geometry}
          material={materials["foto bupati 4"]}
        />
        <mesh
          geometry={nodes.Plane019_3.geometry}
          material={materials["foto bupati 6"]}
        />
        <mesh
          geometry={nodes.Plane019_4.geometry}
          material={materials["foto bupati 7"]}
        />
        <mesh
          geometry={nodes.Plane019_5.geometry}
          material={materials["foto bupati 8"]}
        />
        <mesh
          geometry={nodes.Plane019_6.geometry}
          material={materials["foto bupati 9"]}
        />
        <mesh
          geometry={nodes.Plane019_7.geometry}
          material={materials["foto bupati 5"]}
        />
      </group>
      <group
        position={[-5.57, 0.95, 1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.51, 0.63, 0.84]}
      >
        <mesh
          geometry={nodes.Plane020.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane020_1.geometry}
          material={materials["foto stasiun"]}
        />
        <mesh
          geometry={nodes.Plane020_2.geometry}
          material={materials["foto keresidenan"]}
        />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[8.6, 0.89, 1.97]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[8.6, 0.77, -0.53]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={nodes.Text002.material}
        position={[8.6, 0.89, -2.76]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text003.geometry}
        material={nodes.Text003.material}
        position={[5.9, 0.87, 2.07]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text004.geometry}
        material={nodes.Text004.material}
        position={[5.9, 0.91, 0.6]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text005.geometry}
        material={nodes.Text005.material}
        position={[5.9, 0.91, -0.86]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text006.geometry}
        material={nodes.Text006.material}
        position={[2.85, 1.2, -2.13]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text007.geometry}
        material={nodes.Text007.material}
        position={[2.85, 1.33, 0.8]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text008.geometry}
        material={nodes.Text008.material}
        position={[1.83, 0.3, 4.03]}
        rotation={[2.76, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Text009.geometry}
        material={nodes.Text009.material}
        position={[-1.04, 0.3, 4.03]}
        rotation={[2.76, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Text010.geometry}
        material={nodes.Text010.material}
        position={[-3.9, 0.3, 4.03]}
        rotation={[2.76, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Text011.geometry}
        material={nodes.Text011.material}
        position={[-6.7, 0.3, 4.03]}
        rotation={[2.76, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Text012.geometry}
        material={nodes.Text012.material}
        position={[-6.57, 0.3, 1.17]}
        rotation={[0.38, 0, 0]}
      />
      <mesh
        geometry={nodes.Text013.geometry}
        material={nodes.Text013.material}
        position={[-3.72, 0.3, 1.17]}
        rotation={[0.38, 0, 0]}
      />
      <mesh
        geometry={nodes.Text014.geometry}
        material={nodes.Text014.material}
        position={[2.47, 1.07, 0.65]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text015.geometry}
        material={nodes.Text015.material}
        position={[2.47, 1.07, -0.32]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text016.geometry}
        material={nodes.Text016.material}
        position={[1.74, 0.72, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Text017.geometry}
        material={nodes.Text017.material}
        position={[0.79, 0.72, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Text018.geometry}
        material={nodes.Text018.material}
        position={[-0.18, 0.72, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Text019.geometry}
        material={nodes.Text019.material}
        position={[-1.12, 0.72, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Text020.geometry}
        material={nodes.Text020.material}
        position={[-2.07, 0.72, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Text021.geometry}
        material={nodes.Text021.material}
        position={[-3.04, 0.72, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Text022.geometry}
        material={nodes.Text022.material}
        position={[-3.99, 0.72, -1.88]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Text023.geometry}
        material={materials["Material.011"]}
        position={[8.55, 1.52, -0.93]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text024.geometry}
        material={materials["Material.011"]}
        position={[5.85, 1.47, 3.36]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Text025.geometry}
        material={materials["Material.011"]}
        position={[4.17, 1.14, 4.27]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Text026.geometry}
        material={materials["Material.011"]}
        position={[2.52, 1.51, 2.19]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-4.58, 1.04, -2.92]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.11, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-4.58, 1.04, -2.92]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.11, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-4.58, 1.04, -2.92]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.11, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-4.58, 1.04, -2.92]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.11, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-4.58, 1.04, -2.92]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.11, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("./models/KontenSideMuseum.glb");
