/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/PetaPurwakarta.glb
*/

import React, { useRef, useState, useE } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function PetaPurwakarta(props) {
  const pleredRef = useRef();
  const pwkRef = useRef();
  const jatiluhurRef = useRef();
  const sukataniRef = useRef();
  const sukasariRef = useRef();
  const cibatuRef = useRef();
  const bbcRef = useRef();
  const cibungurRef = useRef();
  const tegalwaruRef = useRef();
  const bojongRef = useRef();
  const sukataniRdf = useRef();
  const campakaRef = useRef();
  const darangdanRef = useRef();
  const kiarapedesRef = useRef();
  const maniisRef = useRef();
  const pswRef = useRef();
  const ponsalRef = useRef();
  const [hovered, setHovered] = useState(false);

  useFrame(() => {
    if (hovered) {
      pleredRef.current.scale.x =
        pleredRef.current.scale.y =
        pleredRef.current.scale.z +=
          0.01;
      pleredRef.current.scale.x = Math.min(pleredRef.current.scale.x, 1.7);
      pleredRef.current.scale.y = Math.min(pleredRef.current.scale.y, 1.7);
      pleredRef.current.scale.z = Math.min(pleredRef.current.scale.z, 1.7);
    } else {
      pleredRef.current.scale.x =
        pleredRef.current.scale.y =
        pleredRef.current.scale.z -=
          0.1;
      pleredRef.current.scale.x = Math.max(pleredRef.current.scale.x, 1.33);
      pleredRef.current.scale.y = Math.max(pleredRef.current.scale.y, 1.33);
      pleredRef.current.scale.z = Math.max(pleredRef.current.scale.z, 1.33);
    }
  });

  const { nodes, materials } = useGLTF("./models/PetaPurwakarta.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <mesh
        geometry={nodes.Plered.geometry}
        material={materials["Material.001"]}
        position={[-0.54, 0.99, 1.14]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
        ref={pleredRef}
        onPointerOver={() => setHovered(true)}
        onPointerOut={() => setHovered(false)}
      />
      <mesh
        geometry={nodes.tegalwaru.geometry}
        material={materials["Material.001"]}
        position={[-1.16, 1.16, 0.9]}
        rotation={[0.54, 0, 0]}
        scale={[0.05, 0.22, 0.22]}
      />
      <mesh
        geometry={nodes.Jatiluhur.geometry}
        material={materials["Material.001"]}
        position={[-1, 1.46, 0.42]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Sukasari.geometry}
        material={materials["Material.001"]}
        position={[-1.83, 1.53, 0.27]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Sukatani.geometry}
        material={materials["Material.001"]}
        position={[-0.24, 1.3, 0.6]}
        rotation={[0.54, 0, 0]}
        scale={[0.05, 0.22, 0.22]}
      />
      <mesh
        geometry={nodes.darangdan.geometry}
        material={materials["Material.001"]}
        position={[0.1, 0.69, 1.59]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Bojong.geometry}
        material={materials["Material.001"]}
        position={[1.36, 0.7, 1.67]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Wanayasa.geometry}
        material={materials["Material.001"]}
        position={[1.79, 0.92, 1.23]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Kiarapedes.geometry}
        material={materials["Material.001"]}
        position={[2.24, 1.16, 0.9]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Cibatu.geometry}
        material={materials["Material.001"]}
        position={[1.75, 1.79, -0.16]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Campaka.geometry}
        material={materials["Material.001"]}
        position={[1.32, 2.07, -0.55]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Bungursari.geometry}
        material={materials["Material.001"]}
        position={[0.8, 2.33, -1.06]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Babakancikao.geometry}
        material={materials["Material.001"]}
        position={[0.02, 2.08, -0.57]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Pasawahan.geometry}
        material={materials["Material.001"]}
        position={[0.88, 1.52, 0.35]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Maniis.geometry}
        material={materials["Material.001"]}
        position={[-1.72, 0.75, 1.52]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Purwakarta.geometry}
        material={materials["Material.001"]}
        position={[0.58, 1.81, -0.1]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
      <mesh
        geometry={nodes.Pondok_Salam.geometry}
        material={materials["Material.001"]}
        position={[1.2, 1.23, 0.78]}
        rotation={[0.54, 0, 0]}
        scale={1.33}
      />
    </group>
  );
}

useGLTF.preload("./models/PetaPurwakarta.glb");
