/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/models/tembokInfo2.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function TembokInfo2(props) {
  const { nodes, materials } = useGLTF("./models/tembokInfo2.glb");
  return (
    <group
      {...props}
      dispose={null}
      castShadow
      position={props.position}
      scale={props.scale}
      rotation={props.rotation}
    >
      <group position={[0.04, 2.06, -0.51]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Plane001_3.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Plane001_4.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Plane001_5.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Plane001_6.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Plane001_7.geometry}
          material={materials["Material.008"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/tembokInfo2.glb");
